### ISSUE TITLE
hash function is not available

### ISSUE THREAD

**Issue by RayBB** [patrickmn/osg#11]
After downloading the binary and running I'm getting the follow error. 

Any idea why?

```
admin@dell-lat ~/Downloads/osg $ ./osg sitemap.xml patrickmn.com
panic: crypto: requested hash function is unavailable

goroutine 3 [running]:
crypto.Hash.New(0x3800000005, 0x40a6b5, 0x7fd2b2efa3ff, 0x10)
	/home/patrick/apps/go/src/pkg/crypto/crypto.go:62 +0x95
crypto/x509.(*Certificate).CheckSignature(0xf8400c1580, 0x7fd200000004, 0xf84011400e, 0x10d600000438, 0xf84011445a, ...)
	/home/patrick/apps/go/src/pkg/crypto/x509/x509.go:391 +0x68
crypto/x509.(*Certificate).CheckSignatureFrom(0xf8400c12c0, 0xf8400c1580, 0x0, 0x0, 0xf840121538, ...)
	/home/patrick/apps/go/src/pkg/crypto/x509/x509.go:370 +0x15a
crypto/x509.(*CertPool).findVerifiedParents(0xf840122660, 0xf8400c12c0, 0x0, 0x0, 0x60, ...)
	/home/patrick/apps/go/src/pkg/crypto/x509/cert_pool.go:44 +0x17d
crypto/x509.(*Certificate).buildChains(0xf8400c12c0, 0xf840202cc0, 0x7fd2b2efa698, 0x100000001, 0x7fd2b2efa6b0, ...)
	/home/patrick/apps/go/src/pkg/crypto/x509/verify.go:198 +0x1c0
crypto/x509.(*Certificate).Verify(0xf8400c12c0, 0x0, 0x0, 0xf840122660, 0xf840122700, ...)
	/home/patrick/apps/go/src/pkg/crypto/x509/verify.go:177 +0x1c1
crypto/tls.(*Conn).clientHandshake(0xf840109000, 0x0, 0x0, 0x7fd2b408a100)
	/home/patrick/apps/go/src/pkg/crypto/tls/handshake_client.go:117 +0xfab
----- stack segment boundary -----
crypto/tls.(*Conn).Handshake(0xf840109000, 0x0, 0x0, 0xf840109000)
	/home/patrick/apps/go/src/pkg/crypto/tls/conn.go:808 +0xdc
net/http.(*Transport).getConn(0xf84005dac0, 0xf84005c960, 0xf84005c960, 0x0, 0x0, ...)
	/home/patrick/apps/go/src/pkg/net/http/transport.go:369 +0x4aa
net/http.(*Transport).RoundTrip(0xf84005dac0, 0xf8400b70c0, 0x16, 0x0, 0x0, ...)
	/home/patrick/apps/go/src/pkg/net/http/transport.go:155 +0x2ba
net/http.send(0xf8400b70c0, 0xf84005a7e0, 0xf84005dac0, 0x0, 0x0, ...)
	/home/patrick/apps/go/src/pkg/net/http/client.go:133 +0x3ca
net/http.(*Client).doFollowingRedirects(0x71be18, 0xf8400b7000, 0xf8400c4000, 0x0, 0x0, ...)
	/home/patrick/apps/go/src/pkg/net/http/client.go:227 +0x5e2
net/http.(*Client).Do(0x71be18, 0xf8400b7000, 0x726573550000000a, 0x0, 0x0, ...)
	/home/patrick/apps/go/src/pkg/net/http/client.go:100 +0x7e
main.Get(0xf840069c40, 0x7fd200000015, 0x0, 0x15, 0xf840069c60, ...)
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:321 +0x15a
main.(*Crawler).Crawl(0xf840069980, 0xf840000230, 0xf840000310, 0x5e3f74, 0x0, ...)
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:111 +0x5b1
main._func_004(0xf840077280, 0xf840077268, 0xf840077270, 0x0, 0x0, ...)
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:347 +0x72
created by main.generateSitemap
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:348 +0x31f

goroutine 1 [runnable]:
main.generateSitemap(0x7ffd06f6caed, 0xb, 0xf840077250, 0x100000001, 0x0, ...)
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:397 +0x5c7
main.main()
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:455 +0xcb0

goroutine 2 [syscall]:
created by runtime.main
	/home/patrick/apps/go/src/pkg/runtime/proc.c:221

goroutine 4 [runnable]:
sync.runtime_Semacquire(0xf840077430, 0xf840077430)
	/home/patrick/apps/go/src/pkg/runtime/zsema_amd64.c:146 +0x25
sync.(*WaitGroup).Wait(0xf840069940, 0x4136b8)
	/home/patrick/apps/go/src/pkg/sync/waitgroup.go:78 +0xf2
main._func_005(0xf840077260, 0xf840077258, 0x0, 0x0)
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:391 +0x28
created by main.generateSitemap
	/home/patrick/Dropbox/Projects/go/src/github.com/pmylund/osg/main.go:393 +0x58e

goroutine 5 [syscall]:
syscall.Syscall6()
	/home/patrick/apps/go/src/pkg/syscall/asm_linux_amd64.s:40 +0x5
syscall.EpollWait(0xf800000007, 0xf8400bd010, 0xa0000000a, 0xffffffff, 0xc, ...)
	/home/patrick/apps/go/src/pkg/syscall/zerrors_linux_amd64.go:1781 +0xa1
net.(*pollster).WaitFD(0xf8400bd000, 0xf84005b1c0, 0x0, 0x0, 0x0, ...)
	/home/patrick/apps/go/src/pkg/net/fd_linux.go:146 +0x110
net.(*pollServer).Run(0xf84005b1c0, 0x0)
	/home/patrick/apps/go/src/pkg/net/fd.go:236 +0xe4
created by net.newPollServer
	/home/patrick/apps/go/src/pkg/net/newpollserver.go:35 +0x382

goroutine 6 [chan receive]:
net.(*pollServer).WaitRead(0xf84005b1c0, 0xf8400b8120, 0xf84005c690, 0xb, 0x1, ...)
	/home/patrick/apps/go/src/pkg/net/fd.go:268 +0x73
net.(*netFD).Read(0xf8400b8120, 0xf8400bf000, 0x100000001000, 0xffffffff, 0xf84005a450, ...)
	/home/patrick/apps/go/src/pkg/net/fd.go:428 +0x1ec
net.(*TCPConn).Read(0xf8400773f8, 0xf8400bf000, 0x100000001000, 0xe7000000000, 0x0, ...)
	/home/patrick/apps/go/src/pkg/net/tcpsock_posix.go:87 +0xce
bufio.(*Reader).fill(0xf84005b300, 0xf840001be0)
	/home/patrick/apps/go/src/pkg/bufio/bufio.go:77 +0xf0
bufio.(*Reader).Peek(0xf84005b300, 0xf800000001, 0xf8400c4001, 0x0, 0x0, ...)
	/home/patrick/apps/go/src/pkg/bufio/bufio.go:102 +0xbc
net/http.(*persistConn).readLoop(0xf840084d80, 0x0)
	/home/patrick/apps/go/src/pkg/net/http/transport.go:521 +0xab
created by net/http.(*Transport).getConn
	/home/patrick/apps/go/src/pkg/net/http/transport.go:382 +0x5df

```

**Comment by Martin-Eckleben** [comment]
+1
